### ISSUE TITLE
Add section: focus management

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/ember-a11y-for#8]
Add a section on focus management. It should include: 

- [x] what the browser naturally gives you
- [x] browsing mode vs focus mode in screen readers
- [x] focus should return to the place it came from 
- [x] how focus works in Ember
- [x] addons to consider

**Comment by glunn** [comment]
👋 Hi @MelSumner, found this via the `hacktoberfest` tag and would love to contribute. I started adding some WIP content here: https://github.com/MelSumner/ember-a11y-for/pull/13
Please feel free to use (or not) any of that as you see fit, all feedback appreciated : )
